services:
  _defaults:
    autowire: true
    autoconfigure: true
  kiwi.contao.responsive.frontend:
    class: Kiwi\Contao\ResponsiveBaseBundle\Service\ResponsiveFrontendService
  Kiwi\Contao\ResponsiveBaseBundle\EventListener\LoadDataContainerListener: ~
  Kiwi\Contao\ResponsiveBaseBundle\EventListener\ParseTemplateListener: ~
  Kiwi\Contao\ResponsiveBaseBundle\Twig\ResponsiveExtension:
    arguments:
      - '@kiwi.contao.responsive.frontend'
    tags:
      - 'twig.extension'