services:
  _defaults:
    autowire: true
    autoconfigure: true
  kiwi.contao.responsive.frontend:
    public: true
    class: Kiwi\Contao\ResponsiveBaseBundle\Service\ResponsiveFrontendService
  Kiwi\Contao\ResponsiveBaseBundle\Controller\ResponsiveAssetsController:
    public: true
    arguments:
      - '@contao.framework'
      - '@twig'
  Kiwi\Contao\ResponsiveBaseBundle\EventListener\LoadDataContainerListener: ~
  Kiwi\Contao\ResponsiveBaseBundle\EventListener\ParseTemplateListener: ~
  Kiwi\Contao\ResponsiveBaseBundle\EventListener\GetAllEventsListener: ~
  Kiwi\Contao\ResponsiveBaseBundle\EventListener\GeneratePageListener: ~
  Kiwi\Contao\ResponsiveBaseBundle\EventListener\GetFrontendModuleListener: ~
  Kiwi\Contao\ResponsiveBaseBundle\Twig\ResponsiveExtension:
    arguments:
      - '@kiwi.contao.responsive.frontend'
    tags:
      - 'twig.extension'