services:
  Kiwi\Contao\ResponsiveBase\EventListener\DcGeneral\UpdateDataDefinition:
    tags:
      - name: kernel.event_listener
        event: dc-general.factory.build-data-definition
        method: addResponsiveFields
        priority: -5000